### ISSUE TITLE
获取PA出现错误！

### ISSUE THREAD

**Issue by Mijjj** [billjyc/pocket48#14]
C:\Users\Administrator\Desktop\pocket48-coolq>python main.py
[2020-11-09 02:55:41,391] [DEBUG] [my_logger.py - <module> - line: 18] abcdefg
[2020-11-09 02:55:42,089] [DEBUG] [main.py - <module> - line: 27] 读取成员信息
[2020-11-09 02:55:42,092] [DEBUG] [main.py - <module> - line: 42] room_msg_lite_groups: []
[2020-11-09 02:55:42,092] [DEBUG] [main.py - <module> - line: 43] room_msg_groups: ['***']
[2020-11-09 02:55:42,092] [DEBUG] [main.py - <module> - line: 42] room_msg_lite_groups: []
[2020-11-09 02:55:42,092] [DEBUG] [main.py - <module> - line: 43] room_msg_groups: ['***']
[2020-11-09 02:55:42,170] [INFO] [base.py - add_job - line: 440] Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2020-11-09 02:55:42,170] [INFO] [base.py - add_job - line: 440] Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2020-11-09 02:55:42,175] [INFO] [base.py - add_job - line: 440] Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2020-11-09 02:55:42,176] [INFO] [base.py - add_job - line: 440] Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2020-11-09 02:55:42,177] [INFO] [pocket48_plugin.py - update_pa - line: 87] 更新pa值
Traceback (most recent call last):
  File "main.py", line 51, in <module>
    import pocket48_plugin
  File "C:\Users\Administrator\Desktop\pocket48-coolq\pocket48_plugin.py", line 104, in <module>
    update_pa()
  File "C:\Users\Administrator\Desktop\pocket48-coolq\pocket48_plugin.py", line 89, in update_pa
    global_config.POCKET48_JSON['pa_token'])
  File "C:\Users\Administrator\Desktop\pocket48-coolq\utils\util.py", line 271, in generate_pa2
    raise RuntimeError('获取PA出现错误！')
RuntimeError: 获取PA出现错误！

**Comment by billjyc** [comment]
因为PA值是调用接口的，里面(global_config.POCKET48_JSON)的用户名和token的换成你自己的

813613889
加这个QQ群，找一个叫”Lgyzero“的大佬，他搞了个接口，可以获取PA值，（把信息提供给他，他会给你一个token来调用接口）
